name: 05 - 2 - Event Filters and Activity Types
on: 
    workflow_dispatch
jobs: 
    echo: 
        runs-on: windows-latest
        steps:
            - name: first job
              run: echo "Running whenever a PR is closedd"
